name: Probo Law Firm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Frontend Dependencies
      run: npm ci
    - name: Build Frontend
      run: npm run build
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
